export const ADD_MATERIALS = "ADD_MATERIALS";
export const ADD_MATERIALS_FROM_CHECKBOX = "ADD_MATERIALS_FROM_CHECKBOX";
export const SUBTRACT_MATERIALS = "SUBTRACT_MATERIALS";

export const RESET = "RESET";
export const SET_SHIP = "SET_SHIP";

export const UPDATE_GUNPORTS = "UPDATE_GUNPORTS";
